### ISSUE TITLE
invalid hook call

### ISSUE THREAD

**Issue by melissacinta** [sifatul/react-share-social#13]
Is any other person having this issue? i keep getting invalid hook call when i try to call the share social component
![image](https://user-images.githubusercontent.com/18717315/208398303-2812b52a-0a38-4ac8-88c8-4c60c86f2a13.png)

![image](https://user-images.githubusercontent.com/18717315/208397962-35888461-6d45-4d62-80e4-5e6684a0d4fa.png)

**Comment by AleidS** [comment]
yes getting the same error

**Comment by Sergecodes** [comment]
same. can't even use the package

**Comment by AleidS** [comment]
@Sergecodes I ended up using this instead https://github.com/sakerhetspolisen/react-share-on-social

**Comment by Sergecodes** [comment]
@AleidS  you're a life saver! :) Thanks

**Comment by sifatul** [comment]
thank you guys for creating the issue. issue resolved in v0.1.59
