### ISSUE TITLE
Feature suggestion. Allow prop to hide copy box

### ISSUE THREAD

**Issue by ErikRobles** [sifatul/react-share-social#3]
Just as a feature request, would be nice to be able to hide the copy box (the black box that appears under the icons) either via props or through a css call. My particular reason was due to styling differences. When trying to target the css via classes and then running the react build, those css classes are lost and thus, the stylings do not get applied. So, if we can either hide the box altogether or allow some custom styling, I think it would be a great addition to your already wonderful plugin. Thank you.

**Comment by technophilix** [comment]
Just use  to App.css

makeStyles-copyContainer-5{

  display: none !important;
}

**Comment by ErikRobles** [comment]
Thank you @technophilix That solution worked great in local but for some reason, when compiled, those css targets get replaced by a new class name and no longer work. Since they are never the same classes for each build, there is no way of targeting them except in your local environment.

**Comment by technophilix** [comment]
Sorry @ErikRobles  it is my bad. Can you try for

.jss5{

  display: none !important;
}

for one time?

**Comment by sifatul** [comment]
@ErikRobles  thanks for your suggestion. @technophilix also thanks for trying to help. 
With the latest update, you can now hide copy box. 


```const style = {
  copyContainer: {
    border: '1px solid blue',
    background: 'rgb(0,0,0,0.7)',
    display: 'none'
  }, 
};
```

and passing the style to the component is same like before. 

```
<ShareSocial 
  url ="url_to_share.com"
  socialTypes= {['facebook','twitter']}
  style={style}
/>

```
