### ISSUE TITLE
update to react18 and use react-share latest

### ISSUE THREAD

**Issue by sifatul** [sifatul/react-share-social#30]
Need contributor to update the following packages and make the build work `npm run build`

```javascript
"react": "^18"
"react-share": "^5.1.0"
```

**Comment by theDevSoham** [comment]
Hi @sifatul . So I needed this package for my website in next@14. I have worked on the upgrade, request you to check the [PR#31](https://github.com/sifatul/react-share-social/pull/31). Though I found an alternate named [next-share](https://www.npmjs.com/package/next-share), still please check the PR and let me know if this issue you addressed is solved. Cheers✨

**Comment by sifatul** [comment]
Hi @theDevSoham thank you for the PR. LGTM. will test and publish if all ok.

**Comment by sifatul** [comment]
published v0.1.69
